[package]
name = "log-json-simple"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json_log = "0.2.1"
log = { version = "0.4.21", features = ["kv", "kv_unstable"] }
